server: 
  port: 8081
  error:
    include-message: always
spring:
  mail:
    host: smtp.qq.com
    username: 2587879285@qq.com
    password: cwhjksudhpjjecgg
    title: "界面注册验证码"
    template: "您的注册验证码为：%s，五分钟内有效"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
auth:
  handler:
    email: "email"
    code: "code"
    password: "password"
    email-code-key: "EMAIL_CODE_KEY"
    register-email-key: "REGISTER_EMAIL"
    captcha-key: "captcha"
    login-user-key: "LOGIN_USER"
    msg1: "邮箱验证码错误或过期"
    msg2: "注册邮箱与发送验证码邮箱不一致"
    msg3: "图片验证码错误或过期"
    msg4: "登录成功"
    msg5: "该邮箱已注册"
    msg6: "注册成功"
    msg7: "该邮箱未注册"
    msg8: "密码错误"
    msg9: "登录成功"

captch:
  captcha_str: "captcha"
  pragma: "Pragma"
  no_cache: "No-cache"
  cache_control: "Cache-Control"
  expires: "Expires"
  content_type: "image/jpeg"
  jpeg: "jpeg"

emailservice:
  captcha_str: "captcha"
  email_code_key: "email"
  session_email_code: "EMAIL_CODE_KEY"
  session_register_email: "REGISTER_EMAIL"
  msg_image: "图片验证码错误或者过期"
  msg_mail: "邮箱验证码发送成功"